# Generated by Django 4.1.7 on 2023-03-13 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_story_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Story',
            new_name='StoryModel',
        ),
    ]
