# Generated by Django 4.1.7 on 2023-03-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_story_storymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='storymodel',
            name='relationship',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
