# Generated by Django 4.1.7 on 2023-03-14 23:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_storymodel_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storymodel',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
